---
kind: pipeline
name: react-ci-cd

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install
      - npm run build
  - name: test
    image: node:alpine
    commands:
      - npm run test
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: drone1

