---
kind: pipeline
name: react-ci-cd

steps:
  - name: deps
    image: node:alpine
    commands:
      - npm install
  - name: build
    image: node:alpine
    commands:
      - npm run build
  - name: test
    image: node:alpine
    commands:
      - npm run test
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: api_github
      files: *
    when:
      event: [toast]
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: drone1

